# Generated by Django 5.0 on 2023-12-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajeev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
